"""initial setup

Revision ID: 223357317ee4
Revises: 
Create Date: 2026-07-11 20:41:27.088456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '223357317ee4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'field_name', 'display_name', name='uq_investment_options_asset_field_display_name')
    )
    op.create_index(op.f('ix_investment_options_asset_type'), 'investment_options', ['asset_type'], unique=False)
    op.create_index(op.f('ix_investment_options_display_name'), 'investment_options', ['display_name'], unique=False)
    op.create_index(op.f('ix_investment_options_field_name'), 'investment_options', ['field_name'], unique=False)
    op.create_index(op.f('ix_investment_options_id'), 'investment_options', ['id'], unique=False)
    op.create_table('mutual_fund_data',
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('fund_house', sa.String(length=250), nullable=True),
    sa.Column('scheme_type', sa.String(length=250), nullable=True),
    sa.Column('scheme_category', sa.String(length=250), nullable=True),
    sa.Column('scheme_name', sa.String(length=500), nullable=False),
    sa.Column('isin_growth', sa.String(length=120), nullable=True),
    sa.Column('isin_div_reinvestment', sa.String(length=120), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('nav', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('scheme_code')
    )
    op.create_index(op.f('ix_mutual_fund_data_date'), 'mutual_fund_data', ['date'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_fund_house'), 'mutual_fund_data', ['fund_house'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_isin_div_reinvestment'), 'mutual_fund_data', ['isin_div_reinvestment'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_nav'), 'mutual_fund_data', ['nav'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_scheme_category'), 'mutual_fund_data', ['scheme_category'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_scheme_code'), 'mutual_fund_data', ['scheme_code'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_scheme_name'), 'mutual_fund_data', ['scheme_name'], unique=False)
    op.create_index(op.f('ix_mutual_fund_data_scheme_type'), 'mutual_fund_data', ['scheme_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('billing_cycle_start', sa.Integer(), nullable=True),
    sa.Column('billing_cycle_end', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_accounts_user_id_name')
    )
    op.create_index(op.f('ix_accounts_card_number'), 'accounts', ['card_number'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('income', 'expense', 'transfer', 'investment', 'refund')", name='ck_categories_kind'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'name', name='uq_categories_user_id_kind_name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_kind'), 'categories', ['kind'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_goals_user_id_name')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_name'), 'goals', ['name'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('net_worth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_net_worth_user_id_date')
    )
    op.create_index(op.f('ix_net_worth_id'), 'net_worth', ['id'], unique=False)
    op.create_index(op.f('ix_net_worth_user_id'), 'net_worth', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_id_name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_budgets_user_id_name')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_name'), 'budgets', ['name'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('international_investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('sector_option_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=25), nullable=False),
    sa.Column('security_name', sa.String(length=250), nullable=True),
    sa.Column('market', sa.String(length=25), nullable=False),
    sa.Column('instrument_type', sa.String(length=25), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['sector_option_id'], ['investment_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_international_investments_user_symbol')
    )
    op.create_index(op.f('ix_international_investments_avg_price'), 'international_investments', ['avg_price'], unique=False)
    op.create_index(op.f('ix_international_investments_current_price'), 'international_investments', ['current_price'], unique=False)
    op.create_index(op.f('ix_international_investments_goal_id'), 'international_investments', ['goal_id'], unique=False)
    op.create_index(op.f('ix_international_investments_id'), 'international_investments', ['id'], unique=False)
    op.create_index(op.f('ix_international_investments_instrument_type'), 'international_investments', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_international_investments_market'), 'international_investments', ['market'], unique=False)
    op.create_index(op.f('ix_international_investments_quantity'), 'international_investments', ['quantity'], unique=False)
    op.create_index(op.f('ix_international_investments_sector_option_id'), 'international_investments', ['sector_option_id'], unique=False)
    op.create_index(op.f('ix_international_investments_security_name'), 'international_investments', ['security_name'], unique=False)
    op.create_index(op.f('ix_international_investments_symbol'), 'international_investments', ['symbol'], unique=False)
    op.create_index(op.f('ix_international_investments_user_id'), 'international_investments', ['user_id'], unique=False)
    op.create_table('mutual_fund_investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('category_option_id', sa.Uuid(), nullable=True),
    sa.Column('units', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_option_id'], ['investment_options.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['scheme_code'], ['mutual_fund_data.scheme_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scheme_code', name='uq_mutual_fund_investments_user_scheme_code')
    )
    op.create_index(op.f('ix_mutual_fund_investments_avg_price'), 'mutual_fund_investments', ['avg_price'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_category_option_id'), 'mutual_fund_investments', ['category_option_id'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_goal_id'), 'mutual_fund_investments', ['goal_id'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_id'), 'mutual_fund_investments', ['id'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_scheme_code'), 'mutual_fund_investments', ['scheme_code'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_units'), 'mutual_fund_investments', ['units'], unique=False)
    op.create_index(op.f('ix_mutual_fund_investments_user_id'), 'mutual_fund_investments', ['user_id'], unique=False)
    op.create_table('stock_investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('sector_option_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=25), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('exchange', sa.String(length=25), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['sector_option_id'], ['investment_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_stock_investments_user_symbol')
    )
    op.create_index(op.f('ix_stock_investments_avg_price'), 'stock_investments', ['avg_price'], unique=False)
    op.create_index(op.f('ix_stock_investments_company_name'), 'stock_investments', ['company_name'], unique=False)
    op.create_index(op.f('ix_stock_investments_current_price'), 'stock_investments', ['current_price'], unique=False)
    op.create_index(op.f('ix_stock_investments_exchange'), 'stock_investments', ['exchange'], unique=False)
    op.create_index(op.f('ix_stock_investments_goal_id'), 'stock_investments', ['goal_id'], unique=False)
    op.create_index(op.f('ix_stock_investments_id'), 'stock_investments', ['id'], unique=False)
    op.create_index(op.f('ix_stock_investments_quantity'), 'stock_investments', ['quantity'], unique=False)
    op.create_index(op.f('ix_stock_investments_sector_option_id'), 'stock_investments', ['sector_option_id'], unique=False)
    op.create_index(op.f('ix_stock_investments_symbol'), 'stock_investments', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_investments_user_id'), 'stock_investments', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bills', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_goal_id'), 'transactions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_tag_id'), 'transactions', ['tag_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tag_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_goal_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_stock_investments_user_id'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_symbol'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_sector_option_id'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_quantity'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_id'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_goal_id'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_exchange'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_current_price'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_company_name'), table_name='stock_investments')
    op.drop_index(op.f('ix_stock_investments_avg_price'), table_name='stock_investments')
    op.drop_table('stock_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_user_id'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_units'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_scheme_code'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_id'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_goal_id'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_category_option_id'), table_name='mutual_fund_investments')
    op.drop_index(op.f('ix_mutual_fund_investments_avg_price'), table_name='mutual_fund_investments')
    op.drop_table('mutual_fund_investments')
    op.drop_index(op.f('ix_international_investments_user_id'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_symbol'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_security_name'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_sector_option_id'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_quantity'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_market'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_instrument_type'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_id'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_goal_id'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_current_price'), table_name='international_investments')
    op.drop_index(op.f('ix_international_investments_avg_price'), table_name='international_investments')
    op.drop_table('international_investments')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_name'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_net_worth_user_id'), table_name='net_worth')
    op.drop_index(op.f('ix_net_worth_id'), table_name='net_worth')
    op.drop_table('net_worth')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_name'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_kind'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_card_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mutual_fund_data_scheme_type'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_scheme_name'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_scheme_code'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_scheme_category'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_nav'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_isin_div_reinvestment'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_fund_house'), table_name='mutual_fund_data')
    op.drop_index(op.f('ix_mutual_fund_data_date'), table_name='mutual_fund_data')
    op.drop_table('mutual_fund_data')
    op.drop_index(op.f('ix_investment_options_id'), table_name='investment_options')
    op.drop_index(op.f('ix_investment_options_field_name'), table_name='investment_options')
    op.drop_index(op.f('ix_investment_options_display_name'), table_name='investment_options')
    op.drop_index(op.f('ix_investment_options_asset_type'), table_name='investment_options')
    op.drop_table('investment_options')
    # ### end Alembic commands ###
