"""accounts table updated

Revision ID: 45576cd1f87c
Revises: 37ba20e68d88
Create Date: 2026-06-25 11:14:35.244932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45576cd1f87c'
down_revision: Union[str, Sequence[str], None] = '37ba20e68d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'current_balance')
    # ### end Alembic commands ###
