{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledgr.fullname" . }}-env
  labels:
    {{- include "ledgr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
